language: php
php:
  - '7.2'
  - '7.3'

before_install:
  - printf "\n" | pecl install swoole
  - php --ri swoole
  - composer self-update
  - composer validate

install:
  - composer update --prefer-dist --no-suggest

before_script:
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phpunit