language: php
php:
  - '7.2'
  - '7.3'

before_install:
  - composer self-update
  - composer validate

before_script:
  - phpenv config-rm xdebug.ini
  - printf "\n" | pecl install swoole
  - php --ri swoole

install:
  - composer update --prefer-dist --no-suggest


script:
  - vendor/bin/phpunit