<?php

const RPC_REMOTE_EXECUTE_EXCEPTION = 1001;
const RPC_FUNCTION_INVOKE_EXCEPTION = 1002;
const RPC_FUNCTION_NOT_EXIST_EXCEPTION = 1003;
const RPC_INVALID_RESPONSE_EXCEPTION = 1004;
const RPC_SEND_DATA_EXCEPTION = 1005;
const RPC_UNPACKING_EXCEPTION = 1006;
