<?php
declare(strict_types=1);

namespace HZEX\SimpleRpc\Tests\Unit;

use Exception;

class Process extends \Symfony\Component\Process\Process
{
    public function stop($timeout = 10, $signal = null)
    {
        try {
            return parent::stop($timeout, $signal); // TODO: Change the autogenerated stub
        } catch (Exception $exception) {
            return false;
        }
    }
}
